#usamos a versão 22- alpíne para ser leve e garantir node 22.12+
FROM node:22-alpine

WORKDIR /app
#copiamos,apenas os arquivos de dependencias primeiro (otimiza o cache)
COPY package*.json package-lock.json ./

RUN npm install
#copiamos o restante dos arquivos
COPY . .
# expomos a porta padrao do vite
EXPOSE 5173
#comando para rodar o vite com a flag --host
#isso e obrigatorio para o docker conseguir acessar o serviço interno     
CMD ["npm", "run", "dev", "--", "--host"]   
